package com.networknt.query.handler;

import com.networknt.client.Client;
import com.networknt.exception.ClientException;
import com.networknt.exception.ApiException;
import org.apache.commons.io.IOUtils;
import org.apache.http.client.methods.*;
import org.apache.http.impl.client.CloseableHttpClient;
import org.junit.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
* Generated by swagger-codegen
*/
public class TodosGetHandlerTest {
    @ClassRule
    public static TestQueryServer server = TestQueryServer.getInstance();

    static final Logger logger = LoggerFactory.getLogger(TodosGetHandlerTest.class);

    @Test
    public void testTodosGetHandler() throws ClientException, ApiException {
        CloseableHttpClient client = Client.getInstance().getSyncClient();
        HttpGet httpGet = new HttpGet("http://localhost:8082/v1/todos");
        try {
            CloseableHttpResponse response = client.execute(httpGet);
            int statusCode = response.getStatusLine().getStatusCode();
            String body = IOUtils.toString(response.getEntity().getContent(), "utf8");
            Assert.assertEquals(200, statusCode);
            Assert.assertTrue(body != null);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
