package com.networknt.query.handler;

import com.networknt.client.Client;
import com.networknt.exception.ClientException;
import com.networknt.exception.ApiException;
import org.apache.http.client.methods.*;
import org.apache.http.impl.client.CloseableHttpClient;
import org.junit.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
* Generated by swagger-codegen
*/
public class TodosIdGetHandlerTest {
    @ClassRule
    public static TestQueryServer server = TestQueryServer.getInstance();

    static final Logger logger = LoggerFactory.getLogger(TodosIdGetHandlerTest.class);

    @Test
    public void testTodosIdGetHandler() throws ClientException, ApiException {
        CloseableHttpClient client = Client.getInstance().getSyncClient();
        HttpGet httpGet = new HttpGet("http://localhost:8080/v1/todos/id");
        /*
        Client.getInstance().addAuthorization(httpPost);
        try {
            CloseableHttpResponse response = client.execute(httpGet);
            Assert.assertEquals(200, response.getStatusLine().getStatusCode());
            Assert.assertEquals("getById", IOUtils.toString(response.getEntity().getContent(), "utf8"));
        } catch (Exception e) {
            e.printStackTrace();
        }
        */
    }
}
