package com.networknt.command.handler;

import com.networknt.client.Client;
import com.networknt.exception.ClientException;
import com.networknt.exception.ApiException;
import org.apache.http.client.methods.*;
import org.apache.http.impl.client.CloseableHttpClient;
import org.junit.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
* Generated by swagger-codegen
*/
public class TodosPostHandlerTest {
    @ClassRule
    public static TestCommandServer server = TestCommandServer.getInstance();

    static final Logger logger = LoggerFactory.getLogger(TodosPostHandlerTest.class);

    @Test
    public void testTodosPostHandler() throws ClientException, ApiException {
        CloseableHttpClient client = Client.getInstance().getSyncClient();
        HttpPost httpPost = new HttpPost("http://localhost:8080/v1/todos");
        /*
        Client.getInstance().addAuthorization(httpPost);
        try {
            CloseableHttpResponse response = client.execute(httpPost);
            Assert.assertEquals(200, response.getStatusLine().getStatusCode());
            Assert.assertEquals("add", IOUtils.toString(response.getEntity().getContent(), "utf8"));
        } catch (Exception e) {
            e.printStackTrace();
        }
        */
    }
}
