package com.networknt.command.handler;


import com.networknt.client.Client;
import com.networknt.eventuate.common.impl.JSonMapper;
import com.networknt.eventuate.todolist.common.model.TodoInfo;
import com.networknt.exception.ClientException;
import com.networknt.exception.ApiException;
import org.apache.http.client.methods.*;
import org.apache.http.entity.StringEntity;
import org.apache.http.impl.client.CloseableHttpClient;
import org.junit.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.UnsupportedEncodingException;

/**
* Generated by swagger-codegen
*/
public class TodosPostHandlerTest {
    @ClassRule
    public static TestCommandServer server = TestCommandServer.getInstance();


    static final Logger logger = LoggerFactory.getLogger(TodosPostHandlerTest.class);

    @Test
    public void testTodosPostHandler() throws ClientException, ApiException, UnsupportedEncodingException {

        CloseableHttpClient client = Client.getInstance().getSyncClient();
        HttpPost httpPost = new HttpPost("http://localhost:8083/v1/todos");
       TodoInfo todo = new TodoInfo();
        todo.setTitle(" this is the test todo from junit test");

        String json = JSonMapper.toJson(todo);

     //   Client.getInstance().addAuthorization(httpPost);
        try {
            httpPost.setEntity(new StringEntity(json));
            httpPost.setHeader("Content-type", "application/json");
            CloseableHttpResponse response = client.execute(httpPost);
            Assert.assertEquals(200, response.getStatusLine().getStatusCode());
       } catch (Exception e) {
            e.printStackTrace();
        }

    }
}
