DROP table IF EXISTS TODO;

CREATE  TABLE REFERENCE_REPOSITORY (
  ID varchar(255) PRIMARY KEY,
  REFERENCE_NAME varchar(255),
  DESCRIPTION varchar(255),
  ACTIVE_FLG varchar(1) DEFAULT 'Y'
);

